config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "clouds#index"
#get "/clouds", to: "clouds#index"
 # get "/clouds/:id", to: "clouds#show"
  resources :clouds do
  resources :comments
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cloud.rb
class Cloud < ApplicationRecord
   include Visible

    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :cloud
end

app/models/concerns/visible.rb
  module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end
  
    def archived?
      status == 'archived'
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clouds_controller.rb
class CloudsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @clouds = Cloud.all
  end

  def show
    @cloud = Cloud.find(params[:id])
  end

  def new
    @cloud = Cloud.new
  end

  def create
    @cloud = Cloud.new(cloud_params)

    if @cloud.save
      redirect_to @cloud
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @cloud = Cloud.find(params[:id])
  end

  def update
    @cloud = Cloud.find(params[:id])

    if @cloud.update(cloud_params)
      redirect_to @cloud
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @cloud = Cloud.find(params[:id])
    @cloud.destroy
    redirect_to root_path, status: :see_other
  end
  private
  def cloud_params
    params.require(:cloud).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  
    def create
      @cloud = Cloud.find(params[:cloud_id])
      @comment = @cloud.comments.create(comment_params)
      redirect_to cloud_path(@cloud)
    end


  def destroy
    @cloud = Cloud.find(params[:cloud_id])
    @comment = @cloud.comments.find(params[:id])
    @comment.destroy
    redirect_to cloud_path(@cloud), status: :see_other
  end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body, :status)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/clouds_helper.rb
module CloudsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/clouds/_form.html.erb
<%= form_with model: cloud do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% cloud.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% cloud.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
   <%= form.label :status %><br>
   <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clouds/edit.html.erb
<h1>Edit Cloud</h1>

<%= render "form", cloud: @cloud %>

app/views/clouds/index.html.erb
<h1>Clouds</h1>

Our blog has <%= Cloud.public_count %> Cloud and counting!

<ul>
  <% @clouds.each do |cloud| %>
    <% unless cloud.archived? %>
      <li>
        <%= link_to cloud.title, cloud %>
      </li
    <% end %>
  <% end %>
</ul>

<%= link_to "New Cloud", new_cloud_path %>

app/views/clouds/new.html.erb
<h1>New Cloud</h1>

<%= render "form", cloud: @cloud %>

app/views/clouds/show.html.erb
<h1><%= @cloud.title %></h1>

<p><%= @cloud.body %></p>


<ul>
  <li><%= link_to "Edit", edit_cloud_path(@cloud) %></li>
  <li><%= link_to "Destroy", cloud_path(@cloud), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>
<%= render @cloud.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

   <p>
    <%= link_to "Destroy Comment", [comment.cloud, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @cloud, @cloud.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
     <%= form.label :status %><br>
     <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>